
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 14
#define YY_END_OF_BUFFER 15
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[731] =
    {   0,
        0,    0,    0,    0,    0,    0,   15,   14,   10,   14,
        9,    5,    5,    5,    3,    6,    5,    6,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,   14,   13,   10,   13,
        9,    5,    3,    6,    5,    6,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,   13,   14,   10,   14,    4,    5,
        5,    5,    3,    6,    5,    6,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,   14,    6,    8,    7,   12,    3,

        3,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    2,
        2,    2,    2,    2,    2,    2,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    0,   11,   13,    6,    3,    3,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,   13,   11,    0,
        4,    6,    8,    7,   12,    3,    3,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    0,   11,    4,
       12,    3,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    3,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,   12,    4,    3,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        1,    2,    2,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    1,    2,    2,    1,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    2,    2,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        1,    2,    2,    2,    2,    1,    2,    2,    2,    2,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    1,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   14,   19,   14,   20,   14,   21,   22,   23,
       24,   25,    1,    1,   26,   27,   28,   29,   30,   30,
       31,   30,   32,   30,   30,   33,   30,   34,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       35,    1,   36,    1,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    3,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[739] =
    {   0,
        0, 1661,   65, 1660,  130, 1659, 1663, 1667, 1667, 1638,
     1667, 1667, 1648,  188,  188,  173, 1636, 1635,  195,  202,
      223,  196,  207,  206,  212,  208,  175,  218,  219,  177,
      231,  236,  229,  237,  248,  252, 1656,    0,    0, 1633,
        0,    0,  296,  277, 1632, 1631,  316,  356,  241,  173,
      348,  346,  344,  357, 1603,  348, 1602, 1595, 1609,  355,
      358, 1600, 1598, 1603,  394, 1643, 1642,  300, 1667, 1641,
      402,  405,  412,  413,  416,  417,  441,  481,  377,  252,
      473,  471,  469,  385, 1593,  473, 1592, 1585, 1599,  475,
      481, 1590, 1588, 1593,  247, 1667, 1667, 1667,    0,  529,

      538,  479,  480,  482,  513,  512,  520,  523,  524,  516,
      528,  484,  527,  540,  535,  541,  543,  551,  538,  548,
      553,  556,  554,  558,  566,  568,  569,  571,  581,  573,
      588,  589,  591,  603,  601,  602,  585,  613,  616,  606,
      620, 1635, 1667,    0,    0,  664,  673,    0,    0, 1580,
     1589, 1583, 1591, 1590, 1589, 1579, 1583, 1572, 1576, 1584,
     1570, 1586, 1573, 1579, 1564, 1565, 1562, 1562, 1569, 1565,
     1561, 1558,    0,  477, 1563, 1564,  642, 1560,  632,  253,
     1564, 1555, 1551, 1555,  649,  621, 1560,  694,    0, 1601,
     1667, 1600, 1599, 1598,  670,  695,  704,    0,    0, 1545,

     1554, 1548, 1556, 1555, 1554, 1544, 1548, 1537, 1541, 1549,
     1535, 1551, 1538, 1544, 1529, 1530, 1527, 1527, 1534, 1530,
     1526, 1523,    0,  669, 1528, 1529,  682, 1525,  683,  580,
     1529, 1520, 1516, 1520,  684,  655, 1525,  727, 1566, 1567,
        0,  732,  684,  686,  705,  715,  708,  709,  713,  716,
      720,  721,  736,  733,  728,  731,  751,  744,  749,  746,
      754,  750,  762,  761,  767,  772,  766,  779,  774,  769,
      780,  785,  790,  792,  793,  795,  797,  811,  813,  809,
      810,  821,  825,  817,  869, 1517, 1511, 1517, 1525, 1514,
     1513, 1508, 1517, 1509, 1511, 1520, 1515, 1502,  650, 1517,

     1515, 1511, 1503, 1509, 1495, 1511, 1497, 1501, 1502, 1497,
     1498, 1487, 1485, 1487, 1490, 1497, 1482, 1480, 1480, 1493,
     1492, 1491, 1481, 1485, 1489, 1491, 1480,  842,    0,  876,
     1476, 1470, 1476, 1484, 1473, 1472, 1467, 1476, 1468, 1470,
     1479, 1474, 1461,  816, 1476, 1474, 1470, 1462, 1468, 1454,
     1470, 1456, 1460, 1461, 1456, 1457, 1446, 1444, 1446, 1449,
     1456, 1441, 1439, 1439, 1452, 1451, 1450, 1440, 1444, 1448,
     1450, 1439,  849,  867,  852,  855,  860,  863,  868,  871,
      866,  870,  883,  882,  884,  888,  895,  890,  900,  901,
      906,  908,  912,  911,  922,  923,  887,  933,  935,  934,

      936,  928,  950,  940,  947, 1437, 1453, 1432, 1437, 1440,
     1437, 1438, 1429, 1431, 1421, 1430, 1418, 1426, 1419, 1430,
     1415, 1420, 1417, 1413, 1413, 1412, 1409, 1422, 1412, 1416,
     1421, 1420, 1421,  958, 1408, 1413, 1400, 1413, 1405, 1421,
     1400, 1405, 1408, 1405, 1406, 1397, 1399, 1389, 1398, 1386,
     1394, 1387, 1398, 1383, 1388, 1385, 1381, 1381, 1380, 1377,
     1390, 1380, 1384, 1389, 1388, 1389,  959, 1376, 1381, 1368,
     1381,  955,  958,  954,  965,  969,  968,  971,  982,  987,
      984,  983,  994,  995, 1005,  998, 1000, 1012, 1011, 1022,
     1023, 1024, 1017, 1030, 1035, 1040, 1041, 1043, 1048, 1376,

     1371, 1372, 1370, 1364, 1361, 1360,  384, 1373, 1364, 1365,
     1370, 1361, 1368, 1353, 1352, 1361, 1356, 1364, 1361, 1363,
     1346, 1356, 1359, 1357, 1355, 1347, 1350, 1349, 1344, 1345,
     1343, 1337, 1334, 1333,  826, 1346, 1337, 1338, 1343, 1334,
     1341, 1326, 1325, 1334, 1329, 1337, 1334, 1336, 1319, 1329,
     1332, 1330, 1328, 1320, 1323, 1055, 1029, 1059, 1061, 1056,
     1063, 1058, 1062, 1078, 1074, 1066, 1076, 1082, 1095, 1098,
     1092, 1105, 1102, 1110, 1106, 1103, 1328, 1311, 1324, 1327,
     1318, 1318, 1305, 1306, 1317, 1299, 1301, 1301, 1302, 1313,
     1314, 1316, 1315, 1308, 1313, 1307, 1300, 1307, 1290, 1303,

     1306, 1297, 1297, 1284, 1285, 1296, 1278, 1280, 1280, 1281,
     1292, 1293, 1295, 1294, 1287, 1292, 1286, 1279, 1108, 1109,
     1121, 1122, 1123, 1124, 1140, 1135, 1137, 1148, 1127, 1142,
     1150, 1153, 1266, 1277, 1284, 1272, 1268, 1269, 1278, 1265,
     1262, 1279, 1268, 1258, 1273, 1271, 1252, 1263, 1270, 1258,
     1248, 1235, 1237, 1218, 1214, 1224, 1139, 1117, 1123, 1102,
     1185, 1160, 1161, 1158, 1165, 1168, 1173, 1209, 1098, 1078,
     1073, 1070, 1039, 1017, 1212, 1007,  999,  984,  982,  970,
      968, 1198, 1216, 1217, 1186, 1196, 1192,  989,  970,  937,
      896,  894,  869,  889,  865,  861,  821,  835,  768, 1218,

     1191, 1210, 1199, 1202,  784,    0,  738,  706,  683,  716,
        0,  691,  690,  643, 1203, 1206, 1223,  621,  607,  584,
      553,  539,  513, 1220, 1221,  383,  362,  273,  230, 1667,
      195, 1280, 1284, 1288, 1292, 1296, 1300, 1304
    } ;

static const flex_int16_t yy_def[739] =
    {   0,
      730,    1,  730,    3,  730,    5,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  731,  731,
      731,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,  732,  733,  733,  733,
      733,  733,  733,  733,  733,  733,  730,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,  734,  735,  735,  735,  730,  735,
      735,  735,  735,  735,  735,  735,  730,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,  736,  730,  730,  730,  737,  730,

      730,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,  732,  730,  733,  733,  733,  733,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,  734,  733,  735,
      730,  735,  735,  735,  738,  735,  735,   77,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,  736,  735,  732,
      737,  730,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,  733,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,  738,  737,  735,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   77,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       21,   21,   21,   21,   21,   21,   21,   47,   47,   47,
       47,   47,   47,   47,   77,   77,   77,   77,   77,   77,
       77,   21,   21,   21,   21,   21,   21,   47,   47,   47,
       47,   47,   47,   77,   77,   77,   77,   77,   77,   21,

       21,   21,   21,   21,   47,   47,   47,   47,   47,   77,
       77,   77,   77,   77,   21,   21,   21,   47,   47,   47,
       77,   77,   77,   21,   21,   47,   47,   77,   77,    0,
      730,  730,  730,  730,  730,  730,  730,  730
    } ;

static const flex_int16_t yy_nxt[1733] =
    {   0,
        8,    9,   10,   11,    8,   12,   12,   13,   12,   12,
       12,   12,   14,   15,   15,   15,   15,   15,   15,   15,
       12,   12,   16,   17,   18,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   12,   12,   20,   21,   22,   23,
       24,   25,   26,   27,   19,   28,   19,   29,   19,   30,
       19,   19,   19,   31,   32,   33,   34,   35,   36,   19,
       19,   19,   12,   12,   12,   38,   39,   40,   41,   38,
       42,   42,   13,   42,   42,   42,   42,   14,   43,   43,
       43,   43,   43,   43,   43,   42,   42,   44,   45,   46,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   42,

       42,   48,   49,   50,   51,   52,   53,   54,   55,   47,
       56,   47,   57,   47,   58,   47,   47,   47,   59,   60,
       61,   62,   63,   64,   47,   47,   47,   42,   42,   42,
       66,   67,   68,   69,   66,   70,   70,   71,   70,   70,
       70,   70,   72,   73,   73,   73,   73,   73,   73,   73,
       70,   70,   74,   75,   76,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   70,   70,   78,   79,   80,   81,
       82,   83,   84,   85,   77,   86,   77,   87,   77,   88,
       77,   77,   77,   89,   90,   91,   92,   93,   94,   77,
       77,   77,   70,   70,   70,   98,   96,   96,  103,  100,

       99,  101,  101,  101,  101,  101,  101,  101,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  103,  159,  103,  126,  160,  104,  105,  106,
      107,  103,  108,  130,  109,  110,  102,  102,  102,  102,
      102,  102,  102,  103,  115,  123,  113,  118,  239,  114,
      240,  116,  103,  103,  103,  124,  119,  117,  125,  120,
      127,  121,  103,  103,  103,  103,  103,  128,  103,  129,
      111,  122,  131,  136,  103,  103,  103,  223,  103,  112,
      132,  133,  137,  103,  103,  103,  139,  103,  157,  138,
      317,  134,  103,  103,  135,  103,  141,  158,  140,  103,

      145,  145,  209,  191,  103,  210,  318,  146,  103,  147,
      147,  147,  147,  147,  147,  147,  144,  144,  144,  144,
      144,  144,  144,  192,  144,  144,  144,  144,  223,  148,
      148,  148,  148,  148,  148,  148,  144,  144,  144,  144,
      144,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      144,  144,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  144,  144,
      144,  150,  151,  152,  153,  161,  154,  164,  155,  156,
      173,  166,  162,  167,  169,  189,  165,  174,  163,  178,

      179,  142,  182,  168,  170,  191,  142,  171,  191,  173,
      180,  183,  194,  181,  193,  191,  191,  195,  184,  191,
      191,  584,  219,  196,  207,  197,  197,  197,  197,  197,
      197,  197,  220,  208,  585,  221,  192,  192,  173,  192,
      192,  190,  190,  190,  191,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  198,  198,  198,  198,  198,  198,
      198,  190,  190,  190,  190,  190,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  190,  190,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,

      199,  199,  199,  190,  190,  190,  200,  201,  202,  203,
      211,  204,  214,  205,  206,  223,  216,  212,  217,  228,
      229,  215,  224,  213,  308,  232,  103,  103,  218,  103,
      230,  103,  173,  231,  233,  103,  103,  243,  103,  251,
      103,  234,  242,  242,  242,  242,  242,  242,  242,  100,
      729,  101,  101,  101,  101,  101,  101,  101,  244,  103,
      103,  246,  245,  103,  247,  248,  249,  103,  103,  103,
      103,  103,  103,  250,  103,  103,  103,  252,  255,  103,
      103,  253,  103,  103,  103,  103,  223,  103,  103,  254,
      103,  103,  256,  257,  258,  103,  103,  103,  103,  103,

      103,  262,  259,  103,  103,  103,  728,  103,  263,  260,
      103,  261,  103,  103,  103,  103,  103,  362,  265,  127,
      267,  727,  103,  264,  103,  103,  127,  103,  103,  103,
      266,  268,  103,  363,  272,  103,  103,  103,  103,  271,
      274,  278,  269,  270,  103,  103,  276,  103,  103,  103,
      103,  282,  273,  283,  173,  277,  275,  103,  103,  103,
      103,  280,  103,  103,  279,  284,  325,  103,  326,  103,
      281,  190,  103,  329,  726,  315,  103,  285,  285,  285,
      285,  285,  285,  285,  146,  311,  147,  147,  147,  147,
      147,  147,  147,  316,  323,  189,  312,  313,  191,  723,

      370,  142,  371,  324,  415,  416,  142,  191,  330,  330,
      330,  330,  330,  330,  330,  196,  353,  197,  197,  197,
      197,  197,  197,  197,  223,  356,  360,  722,  239,  368,
      240,  103,  721,  103,  373,  711,  357,  358,  369,  720,
      103,  374,  103,  719,  361,  242,  242,  242,  242,  242,
      242,  242,  103,  375,  376,  103,  103,  377,  378,  380,
      103,  103,  103,  103,  103,  103,  379,  103,  127,  103,
      127,  103,  103,  381,  127,  103,  103,  103,  103,  718,
      103,  127,  385,  103,  103,  382,  383,  103,  384,  103,
      127,  103,  103,  103,  127,  386,  103,  103,  103,  388,

      103,  103,  103,  706,  387,  103,  103,  103,  103,  103,
      103,  127,  389,  390,  103,  127,  103,  103,  103,  103,
      714,  103,  103,  103,  391,  393,  103,  103,  103,  392,
      103,  396,  103,  394,  395,  103,  103,  103,  400,  103,
      103,  103,  103,  190,  103,  329,  103,  397,  103,  398,
      399,  103,  127,  103,  401,  403,  103,  103,  103,  402,
      103,  127,  404,  605,  405,  103,  103,  103,  103,  103,
      448,  449,  103,  103,  713,  712,  606,  103,  711,  191,
      711,  103,  285,  285,  285,  285,  285,  285,  285,  330,
      330,  330,  330,  330,  330,  330,  103,  472,  473,  103,

      475,  476,  103,  474,  710,  103,  477,  103,  103,  478,
      103,  103,  127,  103,  103,  103,  103,  103,  103,  103,
      479,  709,  103,  103,  103,  480,  103,  103,  481,  103,
      103,  483,  492,  708,  103,  103,  127,  103,  482,  103,
      103,  484,  103,  103,  103,  127,  103,  103,  103,  485,
      707,  103,  486,  103,  706,  103,  103,  103,  103,  103,
      487,  488,  103,  490,  103,  489,  127,  103,  103,  103,
      103,  495,  493,  491,  494,  103,  496,  127,  103,  103,
      103,  103,  103,  103,  103,  706,  497,  103,  127,  103,
      103,  103,  103,  498,  103,  499,  103,  103,  524,  552,

      556,  558,  103,  103,  705,  103,  103,  557,  525,  553,
      103,  103,  103,  559,  103,  103,  103,  699,  103,  563,
      698,  103,  560,  561,  103,  103,  562,  103,  565,  103,
      567,  103,  564,  566,  103,  127,  697,  223,  103,  103,
      103,  103,  103,  103,  127,  103,  127,  103,  223,  223,
      103,  103,  103,  568,  103,  569,  103,  570,  103,  103,
      127,  103,  127,  571,  103,  127,  693,  103,  103,  103,
      103,  103,  127,  103,  127,  572,  103,  103,  103,  103,
      103,  573,  103,  574,  127,  103,  103,  103,  103,  692,
      103,  103,  575,  576,  127,  103,  103,  103,  620,  103,

      619,  621,  103,  103,  103,  103,  103,  622,  103,  103,
      103,  103,  103,  103,  623,  103,  127,  103,  103,  103,
      127,  103,  625,  103,  691,  103,  173,  173,  628,  103,
      103,  127,  103,  624,  103,  127,  626,  627,  103,  103,
      173,  629,  103,  223,  127,  103,  630,  631,  103,  103,
      632,  103,  103,  103,  103,  103,  661,  103,  103,  103,
      127,  103,  103,  223,  103,  103,  103,  127,  103,  103,
      103,  103,  662,  681,  666,  664,  663,  103,  103,  103,
      103,  127,  103,  103,  103,  665,  680,  103,  127,  103,
      127,  103,  127,  103,  127,  103,  103,  103,  667,  682,

      103,  683,  127,  684,  103,  103,  103,  103,  103,  103,
      127,  127,  103,  700,  103,  103,  103,  103,  686,  685,
      103,  103,  687,  688,  103,  689,  694,  690,  695,  103,
      696,  701,  103,  103,  701,  703,  716,  701,  103,  103,
      702,  103,  103,  103,  704,  103,  103,  103,  103,  103,
      103,  715,  103,  127,  103,  103,  724,  103,  717,  103,
      725,  679,  103,  103,  103,  103,  103,  103,  127,  223,
      103,  223,  103,  103,  103,  127,  103,  103,  223,  103,
      142,  142,  142,  142,  144,  144,  678,  144,  188,  188,
      188,  188,  190,  190,  190,  190,  238,  238,  238,  238,

      241,  677,  241,  241,  328,  328,  328,  328,  676,  223,
      675,  223,  173,  173,  674,  673,  672,  173,  173,  173,
      671,  670,  669,  173,  668,  173,  660,  659,  658,  223,
      657,  656,  655,  654,  223,  223,  653,  652,  223,  223,
      651,  650,  649,  648,  647,  223,  223,  646,  645,  644,
      173,  643,  642,  641,  640,  173,  173,  639,  638,  173,
      173,  637,  636,  635,  634,  633,  173,  173,  618,  617,
      616,  615,  614,  223,  223,  613,  223,  223,  223,  612,
      611,  610,  223,  223,  223,  609,  608,  607,  604,  603,
      602,  601,  600,  599,  598,  597,  596,  595,  594,  593,

      173,  173,  592,  173,  173,  173,  591,  590,  589,  173,
      173,  173,  588,  587,  586,  583,  582,  581,  580,  579,
      578,  577,  223,  555,  554,  223,  551,  550,  549,  548,
      547,  546,  223,  545,  544,  543,  542,  541,  223,  223,
      540,  539,  538,  537,  536,  223,  535,  534,  533,  532,
      531,  530,  529,  528,  173,  527,  526,  173,  523,  522,
      521,  520,  519,  518,  173,  517,  516,  515,  514,  513,
      173,  173,  512,  511,  510,  509,  508,  173,  507,  506,
      505,  504,  503,  502,  501,  500,  471,  470,  223,  469,
      468,  467,  223,  466,  465,  464,  463,  462,  461,  460,

      459,  458,  457,  456,  223,  455,  223,  454,  453,  452,
      223,  223,  451,  450,  223,  223,  447,  223,  223,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  437,  173,
      436,  435,  434,  173,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  173,  422,  173,  421,  420,
      419,  173,  173,  418,  417,  173,  173,  414,  173,  173,
      413,  412,  411,  410,  409,  408,  407,  406,  143,  191,
      372,  367,  366,  365,  364,  359,  355,  354,  352,  223,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,

      331,  191,  191,  191,  191,  327,  322,  321,  320,  319,
      314,  310,  309,  307,  173,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  143,  237,  236,  235,
      227,  226,  225,  222,  191,  191,  191,  187,  186,  185,
      177,  176,  175,  172,  145,  145,  145,  143,   96,   96,
       97,   96,  730,   95,   65,   37,    7,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,

      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730
    } ;

static const flex_int16_t yy_chk[1733] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,   14,   16,   16,  731,   15,

       14,   15,   15,   15,   15,   15,   15,   15,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   20,   20,   20,
       20,   20,   27,   50,   30,   27,   50,   20,   20,   20,
       20,   27,   20,   30,   20,   20,   21,   21,   21,   21,
       21,   21,   21,   22,   23,   26,   22,   24,   95,   22,
       95,   23,   22,   24,   23,   26,   24,   23,   26,   25,
       28,   25,   24,   23,   26,   28,   29,   28,   25,   29,
       21,   25,   31,   33,   28,   29,   33,  729,   31,   21,
       32,   32,   33,   32,   34,   33,   34,   31,   49,   33,
      180,   32,   32,   34,   32,   35,   36,   49,   35,   36,

       44,   44,   80,   68,   35,   80,  180,   43,   36,   43,
       43,   43,   43,   43,   43,   43,   47,   47,   47,   47,
       47,   47,   47,   68,   47,   47,   47,   47,  728,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   48,   48,   48,   48,   51,   48,   52,   48,   48,
       56,   53,   51,   53,   54,   65,   52,   56,   51,   60,

       60,   65,   61,   53,   54,   71,   65,   54,   72,  727,
       60,   61,   72,   60,   71,   73,   74,   72,   61,   75,
       76,  507,   84,   73,   79,   73,   73,   73,   73,   73,
       73,   73,   84,   79,  507,   84,   74,   74,  726,   75,
       76,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,

       77,   77,   77,   77,   77,   77,   78,   78,   78,   78,
       81,   78,   82,   78,   78,   86,   83,   81,   83,   90,
       90,   82,   86,   81,  174,   91,  102,  103,   83,  104,
       90,  112,  174,   90,   91,  102,  103,  104,  104,  112,
      112,   91,  100,  100,  100,  100,  100,  100,  100,  101,
      723,  101,  101,  101,  101,  101,  101,  101,  105,  106,
      105,  107,  106,  110,  108,  109,  110,  107,  106,  105,
      108,  109,  110,  111,  113,  111,  107,  113,  116,  108,
      109,  114,  115,  113,  111,  119,  722,  114,  116,  115,
      117,  115,  117,  118,  119,  120,  114,  116,  118,  117,

      121,  123,  120,  122,  120,  124,  721,  118,  124,  121,
      123,  122,  122,  125,  124,  126,  127,  230,  128,  125,
      130,  720,  125,  126,  126,  127,  128,  128,  129,  130,
      129,  131,  137,  230,  133,  131,  132,  129,  133,  132,
      134,  137,  131,  131,  131,  132,  135,  133,  135,  136,
      134,  140,  133,  140,  719,  136,  134,  135,  136,  134,
      138,  139,  140,  139,  138,  141,  186,  141,  186,  138,
      139,  195,  139,  195,  718,  179,  141,  146,  146,  146,
      146,  146,  146,  146,  147,  177,  147,  147,  147,  147,
      147,  147,  147,  179,  185,  188,  177,  177,  196,  714,

      236,  188,  236,  185,  299,  299,  188,  197,  196,  196,
      196,  196,  196,  196,  196,  197,  224,  197,  197,  197,
      197,  197,  197,  197,  224,  227,  229,  713,  238,  235,
      238,  243,  712,  244,  243,  710,  227,  227,  235,  709,
      243,  244,  244,  708,  229,  242,  242,  242,  242,  242,
      242,  242,  245,  245,  246,  247,  248,  247,  248,  250,
      249,  245,  246,  250,  247,  248,  249,  251,  252,  249,
      251,  246,  250,  253,  254,  255,  251,  252,  256,  707,
      254,  255,  258,  253,  255,  256,  256,  256,  257,  254,
      259,  258,  253,  260,  260,  261,  259,  262,  257,  263,

      258,  261,  260,  705,  262,  259,  262,  257,  264,  263,
      261,  264,  265,  267,  265,  266,  270,  264,  263,  266,
      699,  269,  267,  265,  268,  270,  268,  271,  266,  269,
      269,  273,  272,  271,  272,  268,  271,  273,  277,  274,
      275,  272,  276,  328,  277,  328,  273,  274,  274,  275,
      276,  276,  278,  277,  279,  281,  280,  281,  278,  280,
      279,  282,  283,  535,  284,  280,  281,  278,  282,  279,
      344,  344,  283,  284,  698,  697,  535,  282,  696,  330,
      695,  283,  285,  285,  285,  285,  285,  285,  285,  330,
      330,  330,  330,  330,  330,  330,  373,  373,  374,  375,

      376,  377,  376,  375,  694,  373,  378,  377,  375,  379,
      378,  376,  381,  381,  374,  379,  377,  382,  380,  378,
      380,  693,  381,  374,  379,  382,  382,  380,  383,  384,
      383,  385,  397,  692,  397,  386,  387,  388,  384,  383,
      385,  386,  387,  397,  386,  388,  388,  389,  390,  389,
      691,  387,  390,  391,  690,  392,  389,  390,  394,  393,
      391,  392,  391,  395,  392,  393,  394,  394,  393,  395,
      396,  400,  398,  396,  399,  402,  401,  402,  395,  396,
      398,  400,  399,  401,  402,  689,  401,  404,  405,  398,
      400,  399,  401,  403,  405,  404,  404,  403,  434,  467,

      472,  474,  472,  405,  688,  473,  403,  473,  434,  467,
      474,  472,  475,  475,  473,  477,  476,  681,  478,  479,
      680,  475,  476,  477,  477,  476,  478,  478,  480,  479,
      482,  481,  479,  481,  480,  483,  679,  678,  479,  482,
      481,  483,  484,  480,  484,  486,  485,  487,  677,  676,
      483,  484,  485,  486,  486,  487,  487,  488,  489,  488,
      489,  485,  490,  492,  493,  491,  674,  489,  488,  490,
      491,  492,  493,  493,  494,  495,  557,  494,  490,  491,
      492,  496,  495,  497,  557,  557,  494,  496,  497,  673,
      498,  495,  498,  499,  556,  499,  496,  497,  559,  498,

      558,  560,  556,  560,  499,  562,  558,  561,  559,  563,
      561,  556,  560,  566,  562,  558,  563,  559,  563,  561,
      564,  565,  566,  567,  672,  564,  671,  670,  571,  568,
      565,  567,  567,  565,  564,  568,  569,  570,  568,  571,
      669,  572,  569,  660,  573,  570,  574,  575,  571,  573,
      576,  569,  572,  575,  570,  619,  620,  574,  573,  576,
      621,  572,  575,  659,  619,  620,  574,  619,  621,  622,
      623,  624,  622,  658,  629,  624,  623,  621,  622,  623,
      624,  625,  626,  629,  627,  628,  657,  625,  626,  630,
      631,  626,  627,  627,  632,  628,  625,  631,  630,  661,

      632,  661,  662,  661,  628,  664,  631,  662,  663,  632,
      663,  664,  665,  682,  664,  666,  662,  663,  666,  665,
      667,  665,  667,  668,  666,  668,  675,  668,  675,  667,
      675,  683,  661,  685,  684,  686,  703,  700,  701,  687,
      685,  661,  685,  686,  687,  682,  703,  701,  687,  704,
      715,  702,  686,  716,  682,  703,  715,  702,  704,  715,
      717,  656,  716,  683,  684,  700,  702,  724,  725,  655,
      717,  654,  683,  684,  700,  724,  724,  725,  653,  717,
      732,  732,  732,  732,  733,  733,  652,  733,  734,  734,
      734,  734,  735,  735,  735,  735,  736,  736,  736,  736,

      737,  651,  737,  737,  738,  738,  738,  738,  650,  649,
      648,  647,  646,  645,  644,  643,  642,  641,  640,  639,
      638,  637,  636,  635,  634,  633,  618,  617,  616,  615,
      614,  613,  612,  611,  610,  609,  608,  607,  606,  605,
      604,  603,  602,  601,  600,  599,  598,  597,  596,  595,
      594,  593,  592,  591,  590,  589,  588,  587,  586,  585,
      584,  583,  582,  581,  580,  579,  578,  577,  555,  554,
      553,  552,  551,  550,  549,  548,  547,  546,  545,  544,
      543,  542,  541,  540,  539,  538,  537,  536,  534,  533,
      532,  531,  530,  529,  528,  527,  526,  525,  524,  523,

      522,  521,  520,  519,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  506,  505,  504,  503,  502,
      501,  500,  471,  470,  469,  468,  466,  465,  464,  463,
      462,  461,  460,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  440,  439,  438,  437,  436,  435,  433,  432,
      431,  430,  429,  428,  427,  426,  425,  424,  423,  422,
      421,  420,  419,  418,  417,  416,  415,  414,  413,  412,
      411,  410,  409,  408,  407,  406,  372,  371,  370,  369,
      368,  367,  366,  365,  364,  363,  362,  361,  360,  359,

      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  240,  239,
      237,  234,  233,  232,  231,  228,  226,  225,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,

      200,  194,  193,  192,  190,  187,  184,  183,  182,  181,
      178,  176,  175,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  142,   94,   93,   92,
       89,   88,   87,   85,   70,   67,   66,   64,   63,   62,
       59,   58,   57,   55,   46,   45,   40,   37,   18,   17,
       13,   10,    7,    6,    4,    2,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,

      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730,  730,  730,  730,  730,  730,  730,  730,  730,
      730,  730
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[15] =
    {   0,
0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
#include "parser.tab.h"
#line 1095 "lex.yy.c"

#line 1097 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRING_STATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 26 "scanner.l"


 
#line 30 "scanner.l"
  /* =================================== */
  /*          DEFAULT BEHAVIOR           */
  /* =================================== */ 


#line 1329 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 731 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1667 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "scanner.l"
{
  yylval.string = strdup(yytext);
  return KEYWORD;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "scanner.l"
{
  yylval.string = strdup(yytext);  
  return IDENTIFIER;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "scanner.l"
{
  yylval.num = atoi(yytext); 
  return NUMBER;
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 50 "scanner.l"
{ 
  BEGIN INITIAL;
  yylval.string = strdup(yytext);  
  return STRING_LITERAL;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "scanner.l"
{ 
  return yytext[0];
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 60 "scanner.l"
{
  yylval.string = strdup(yytext);  
  return COMPARE;
}
	YY_BREAK
 
  /* =================================== */
  /*          ERROR HANDLING             */
  /* =================================== */ 

case 7:
YY_RULE_SETUP
#line 71 "scanner.l"
{ BEGIN COMMENT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "scanner.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "scanner.l"
{ BEGIN STRING_STATE; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 76 "scanner.l"
// Ignora quebras de linha
	YY_BREAK
case 11:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 77 "scanner.l"
// Ignora diretivas de pré-processamento - palavras que começam com #
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 78 "scanner.l"
// Ignora comentários de uma única linha (começam com `//`)
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 79 "scanner.l"
// Ignora qualquer coisa após '/*' até encontrar '*/'
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 82 "scanner.l"
{                // Gera um erro informando que o comentário não foi fechado.
    fprintf(stderr, "Erro: Comentário não fechado na linha %d\n", yylineno);
    return 0;
}
	YY_BREAK
case YY_STATE_EOF(STRING_STATE):
#line 87 "scanner.l"
{           // Gera um erro informando que a string não foi fechada.
    fprintf(stderr, "Erro: String não fechada na linha %d\n", yylineno);
    return 0;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 92 "scanner.l"
ECHO;
	YY_BREAK
#line 1510 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 731 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 731 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 730);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 92 "scanner.l"



